### ISSUE TITLE
ServerStarter not seemingly working with any other modpack

### ISSUE THREAD

**Issue by SirOMGitsYOU** [EnigmaticaModpacks/ServerStarter#5]
### Modpack Version

n/a

### Describe your issue.

When trying to use this for my own modpack, or ATM6 or any other modpack it spits out this error:

And only works if I replace back the URL with E6, any insight onto this or is this specific fork locked to your guys' modpacks only because currently the only other ServerStarter fork available that works uses a sketchy method of stealing the Official API key which I'm less inclined on using.

![](https://i.imgur.com/jTL8wvK.png)

### Crash Report

n/a

### Latest Log

n/a

### Have you modified the modpack?

No

### User Modifications

n/a

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
The reason is that the `manifest.json` shipped with Enigmatica 6 was made by us, not through CurseForge. We added a `downloadUrl` field to every mod entry that this ServerStarter fork relies on to download correctly.

The manifest creation can be seen here: https://github.com/EnigmaticaModpacks/ModpackUploader/blob/master/modpack-uploader.ps1#L110

You're very welcome to use the above tool/script to have this fork work with your pack :)

<blockquote><img src="https://opengraph.githubassets.com/c4720ae1cb11fd5ce5cf7dd612c73faa31a669b986088637dc00009591203dcf/EnigmaticaModpacks/ModpackUploader" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/EnigmaticaModpacks/ModpackUploader">ModpackUploader/modpack-uploader.ps1 at master · EnigmaticaModpacks/ModpackUploader</a></strong></div><div>Automation tool for uploading Modpacks to CurseForge. - ModpackUploader/modpack-uploader.ps1 at master · EnigmaticaModpacks/ModpackUploader</div></blockquote>
